# Generated by Django 6.0.4 on 2026-04-09 16:40

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


def seed_admin_manage_policy(apps, schema_editor):
    AuthPolicyRule = apps.get_model("accounts", "AuthPolicyRule")
    for role_name in ("staff", "superuser"):
        AuthPolicyRule.objects.update_or_create(
            resource="admin",
            action="manage",
            subject_type="role",
            subject_value=role_name,
            defaults={"is_allowed": True},
        )


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0004_seed_profile_and_deactivate_policies'),
    ]

    operations = [
        migrations.CreateModel(
            name='Role',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True)),
                ('description', models.TextField(blank=True, default='')),
            ],
        ),
        migrations.CreateModel(
            name='AccessPermission',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('resource', models.CharField(max_length=100)),
                ('action', models.CharField(max_length=100)),
            ],
            options={
                'constraints': [models.UniqueConstraint(fields=('resource', 'action'), name='uniq_access_permission_resource_action')],
            },
        ),
        migrations.CreateModel(
            name='RolePermission',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('access_permission', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='role_grants', to='accounts.accesspermission')),
                ('role', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='role_permissions', to='accounts.role')),
            ],
            options={
                'constraints': [models.UniqueConstraint(fields=('role', 'access_permission'), name='uniq_role_access_permission')],
            },
        ),
        migrations.CreateModel(
            name='UserRole',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('role', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='user_bindings', to='accounts.role')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='user_roles', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'constraints': [models.UniqueConstraint(fields=('user', 'role'), name='uniq_user_role')],
            },
        ),
        migrations.RunPython(seed_admin_manage_policy, migrations.RunPython.noop),
    ]
